name: Build and Release Python Archives

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag name'
        required: true
        default: 'latest'

jobs:
  build-python:
    name: Build Python ${{ matrix.python_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python_version: ['2.7.18', '3.13.1']
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev zlib1g-dev \
            libncurses5-dev libncursesw5-dev libreadline-dev libsqlite3-dev \
            libgdbm-dev libdb5.3-dev libbz2-dev libexpat1-dev liblzma-dev \
            tk-dev libffi-dev wget

      - name: Set up dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install openssl readline sqlite3 xz zlib tcl-tk

      - name: Set up dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install -y visualstudio2022buildtools
          choco install -y visualstudio2022-workload-vctools

      - name: Build Python ${{ matrix.python_version }}
        shell: bash
        run: |
          bash ./scripts/build-python.sh ${{ matrix.python_version }}

      - name: Create archive
        shell: bash
        run: |
          cd dist
          if [ "$RUNNER_OS" = "Windows" ]; then
            7z a python-${{ matrix.python_version }}-windows-${{ runner.arch }}.zip python-${{ matrix.python_version }}/
          else
            tar czf python-${{ matrix.python_version }}-${{ runner.os }}-${{ runner.arch }}.tar.gz python-${{ matrix.python_version }}/
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-${{ matrix.python_version }}-${{ matrix.os }}-${{ runner.arch }}
          path: |
            dist/*.tar.gz
            dist/*.zip
          retention-days: 7

  create-release:
    name: Create GitHub Release
    needs: build-python
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Prepare release assets
        run: |
          mkdir -p release-assets
          find artifacts -type f \( -name "*.tar.gz" -o -name "*.zip" \) -exec cp {} release-assets/ \;
          ls -lh release-assets/

      - name: Get release tag
        id: get_tag
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "tag=${{ github.event.inputs.release_tag }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi

      - name: Generate release notes
        id: release_notes
        run: |
          cat << EOF > release-notes.md
          # Python Archive Release ${{ steps.get_tag.outputs.tag }}
          
          This release includes standalone Python distributions for multiple platforms.
          
          ## Included Python Versions
          - Python 2.7.18 (最后的 Python 2 版本)
          - Python 3.13.1 (最新的 Python 3 稳定版)
          
          ## Platforms
          - Linux (x86_64, ARM64)
          - macOS (x86_64, ARM64)
          - Windows (x86_64)
          
          ## Usage
          Download the appropriate archive for your platform and extract it:
          
          **Linux/macOS:**
          \`\`\`bash
          tar xzf python-<version>-<platform>-<arch>.tar.gz
          cd python-<version>
          ./bin/python --version
          \`\`\`
          
          **Windows:**
          \`\`\`powershell
          Expand-Archive python-<version>-windows-<arch>.zip
          cd python-<version>
          python.exe --version
          \`\`\`
          
          ## Checksums
          SHA256 checksums for verification:
          \`\`\`
          $(cd release-assets && sha256sum * 2>/dev/null || shasum -a 256 *)
          \`\`\`
          EOF

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          name: Python Archive ${{ steps.get_tag.outputs.tag }}
          body_path: release-notes.md
          draft: false
          prerelease: false
          files: release-assets/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate checksums file
        run: |
          cd release-assets
          sha256sum * > SHA256SUMS.txt 2>/dev/null || shasum -a 256 * > SHA256SUMS.txt

      - name: Upload checksums
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          files: release-assets/SHA256SUMS.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
